import type { HourlyThemeId } from "./hourly-themes";

/** Chat-only topics (not hourly themes). */
export type ChatTopicId =
  | "anger"
  | "fear"
  | "marriage"
  | "prayer"
  | "doubt"
  | "guilt"
  | "grief";

/** All curated verse-pool areas (16 hourly themes + 7 chat topics). */
export type ContentAreaId = HourlyThemeId | ChatTopicId;

export const HOURLY_THEME_IDS: HourlyThemeId[] = [
  "love",
  "hope",
  "faith",
  "security",
  "forgiveness",
  "strength",
  "wisdom",
  "joy",
  "trust",
  "grace",
  "mercy",
  "comfort",
  "courage",
  "guidance",
  "patience",
  "peace",
];

export const CHAT_TOPIC_IDS: ChatTopicId[] = [
  "anger",
  "fear",
  "marriage",
  "prayer",
  "doubt",
  "guilt",
  "grief",
];

export const CONTENT_AREA_IDS: ContentAreaId[] = [
  ...HOURLY_THEME_IDS,
  ...CHAT_TOPIC_IDS,
];

/** Keywords used to build pools and detect chat topics. */
export const AREA_KEYWORDS: Record<ContentAreaId, string[]> = {
  love: [
    "love",
    "beloved",
    "charity",
    "love one another",
    "loved us",
    "loveth",
    "upendo",
    "penda",
  ],
  hope: [
    "hope",
    "hope in",
    "hope of",
    "hopeful",
    "expectation",
    "matumaini",
    "tumaini",
  ],
  faith: [
    "faith",
    "believe",
    "believeth",
    "believed",
    "trust in the lord",
    "imani",
    "amini",
  ],
  security: [
    "refuge",
    "fortress",
    "shadow of the almighty",
    "deliver",
    "protect",
    "keep thee",
    "hide me",
    "salama",
    "usalama",
  ],
  forgiveness: [
    "forgive",
    "forgiveness",
    "forgiven",
    "pardon",
    "mercy",
    "reconcile",
    "msamaha",
    "samehe",
  ],
  strength: [
    "strength",
    "strong",
    "strengthen",
    "power",
    "might",
    "mighty",
    "nguvu",
    "weza",
  ],
  wisdom: [
    "wisdom",
    "wise",
    "understanding",
    "prudent",
    "knowledge",
    "instruction",
    "hekima",
    "busara",
  ],
  joy: [
    "joy",
    "joyful",
    "rejoice",
    "glad",
    "gladness",
    "delight",
    "furaha",
    "shangilia",
  ],
  trust: [
    "trust",
    "trust in",
    "lean not",
    "depend",
    "confidence",
    "kuamini",
    "tumaini",
  ],
  grace: [
    "grace",
    "gracious",
    "favour",
    "favor",
    "neema",
  ],
  mercy: [
    "mercy",
    "merciful",
    "compassion",
    "tender mercies",
    "rehema",
    "huruma",
  ],
  comfort: [
    "comfort",
    "comforted",
    "consolation",
    "refuge",
    "faraja",
    "fariji",
  ],
  courage: [
    "courage",
    "courageous",
    "bold",
    "be strong",
    "fear not",
    "be not afraid",
    "ujasiri",
    "jasiri",
  ],
  guidance: [
    "guide",
    "guidance",
    "lead me",
    "lead thee",
    "direct",
    "paths",
    "shepherd",
    "mwongozo",
  ],
  patience: [
    "patience",
    "patient",
    "longsuffering",
    "wait on the lord",
    "endure",
    "subira",
  ],
  peace: [
    "peace",
    "peaceful",
    "rest",
    "quietness",
    "amani",
  ],
  anger: [
    "anger",
    "angry",
    "wrath",
    "slow to anger",
    "provoke",
    "hasira",
    "ghadhabu",
  ],
  fear: [
    "fear not",
    "afraid",
    "anxious",
    "anxiety",
    "trouble",
    "dismayed",
    "ogopa",
    "hofu",
    "wasiwasi",
  ],
  marriage: [
    "husband",
    "wife",
    "marriage",
    "married",
    "adultery",
    "bride",
    "bridegroom",
    "mume",
    "mke",
    "ndoa",
  ],
  prayer: [
    "pray",
    "prayer",
    "prayers",
    "supplication",
    "intercession",
    "omba",
    "sala",
    "ombea",
  ],
  doubt: [
    "doubt",
    "doubted",
    "unbelief",
    "waver",
    "shaka",
    "waswas",
  ],
  guilt: [
    "guilty",
    "guilt",
    "repent",
    "repentance",
    "confess",
    "sin",
    "hatia",
    "toba",
  ],
  grief: [
    "grief",
    "grieve",
    "mourn",
    "mourning",
    "sorrow",
    "weep",
    "huzuni",
    "ombolezo",
  ],
};

export const AREA_LABELS: Record<
  ContentAreaId,
  { en: string; sw: string }
> = {
  love: { en: "Love", sw: "Upendo" },
  hope: { en: "Hope", sw: "Matumaini" },
  faith: { en: "Faith", sw: "Imani" },
  security: { en: "Security", sw: "Usalama" },
  forgiveness: { en: "Forgiveness", sw: "Msamaha" },
  strength: { en: "Strength", sw: "Nguvu" },
  wisdom: { en: "Wisdom", sw: "Hekima" },
  joy: { en: "Joy", sw: "Furaha" },
  trust: { en: "Trust", sw: "Kuamini" },
  grace: { en: "Grace", sw: "Neema" },
  mercy: { en: "Mercy", sw: "Rehema" },
  comfort: { en: "Comfort", sw: "Faraja" },
  courage: { en: "Courage", sw: "Ujasiri" },
  guidance: { en: "Guidance", sw: "Mwongozo" },
  patience: { en: "Patience", sw: "Subira" },
  peace: { en: "Peace", sw: "Amani" },
  anger: { en: "Anger", sw: "Hasira" },
  fear: { en: "Fear & Anxiety", sw: "Hofu na Wasiwasi" },
  marriage: { en: "Marriage", sw: "Ndoa" },
  prayer: { en: "Prayer", sw: "Sala" },
  doubt: { en: "Doubt", sw: "Shaka" },
  guilt: { en: "Guilt & Repentance", sw: "Hatia na Toba" },
  grief: { en: "Grief", sw: "Huzuni" },
};
